print("(c) sebohacker 2013")
print()
print("CALCULATOR")
print("__________")
print("a ? b = x")
print()
a = input("a = >>>")
b = input("b = >>>")
print()
print("a + b = ",a + b)
wait = input("...")
print("a - b = ",a - b)
wait = input("...")
print("a * b = ",a * b)
wait = input("...")
print("a / b = ",a / b)
wait = input("...")
print()
wait = input("...")
